### ISSUE TITLE
Reference List collapses permanently if you edit a reference.

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#368] opened 2017-10-15 00:13 UTC
I just did the update (4.11.0). Not sure if this bug would have also happened before the update. Here is a video:
https://youtu.be/fc-BODbPC58
I try to open a reference to edit it, and it collapses the reference list permanently. It did not do it with the first several references on the list, but seems to do it with every reference beyond about number 6 on the list.

**Comment by dsifford** [comment] 2017-10-15 00:20
That's definitely an uncaught error happening. Thanks for the report.

Can you trigger the issue again and copy over any error logs that happen to show up in the javascript console?

**Comment by metallikat36** [comment] 2017-10-15 00:47
Before triggering the bug:
![image](https://user-images.githubusercontent.com/17968340/31580534-a6682142-b107-11e7-9e9c-cf6e657b639a.png)

After triggering the bug:
![image](https://user-images.githubusercontent.com/17968340/31580537-c5b386d6-b107-11e7-926d-39d19380e05f.png)

**Comment by dsifford** [comment] 2017-10-15 00:59
@metallikat36 Thanks. That's extremely helpful.

I'll give this a closer look tomorrow afternoon.

**Comment by dsifford** [comment] 2017-10-17 00:30
@metallikat36 Would I be able to log in on your site and look at your issue there. I can't reproduce it on my end.

**Comment by metallikat36** [comment] 2017-10-17 00:52
send me a personal email I can send login info to you.

**Comment by metallikat36** [comment] 2017-10-17 00:53
send me a personal email I can send login info to you.

**Comment by dsifford** [comment] 2017-10-17 00:56
dereksifford@gmail.com

**Comment by dsifford** [comment] 2017-10-17 01:14
@metallikat36 I'm not sure how, but that particular reference has a number of properties being stored on it that are not supposed to be there. I'm not sure who would be adding these properties, but they are almost certain to be what is causing the issue...

Example of the properties on a valid reference:

```json
{
    "id": "e21t5ksib9",
    "type": "article-journal",
    "author": [
        {
            "family": "Kuhnert",
            "given": "R"
        },
        {
            "family": "Hecker",
            "given": "H"
        },
        {
            "family": "Poethko-Müller",
            "given": "C"
        },
        {
            "family": "Schlaud",
            "given": "M"
        },
        {
            "family": "Vennemann",
            "given": "M"
        },
        {
            "family": "Whitaker",
            "given": "HJ"
        },
        {
            "family": "Farrington",
            "given": "CP"
        }
    ],
    "PMID": "21337361",
    "journalAbbreviation": "Stat Med",
    "container-title-short": "Stat Med",
    "title": "A modified self-controlled case series method to examine association between multidose vaccinations and death.",
    "volume": "30",
    "issue": "6",
    "page": "666-77",
    "language": "en-US",
    "ISSN": "0277-6715",
    "container-title": "Statistics in medicine",
    "issued": {
        "date-parts": [
            [
                "2011",
                "03",
                "15"
            ]
        ]
    }
}
```

And here's the properties that the affected reference has on it:

```json
{
    "indexed": {
        "date-parts": [
            [
                2017,
                4,
                1
            ]
        ],
        "date-time": "2017-04-01T21:57:18Z",
        "timestamp": 1491083838159
    },
    "reference-count": 0,
    "publisher": "American Medical Association (AMA)",
    "issue": "15",
    "content-domain": {
        "domain": [],
        "crossmark-restriction": false
    },
    "short-container-title": [
        "JAMA"
    ],
    "published-print": {
        "date-parts": [
            [
                2015,
                4,
                21
            ]
        ]
    },
    "DOI": "10.1001/jama.2015.3077",
    "type": "journal-article",
    "created": {
        "date-parts": [
            [
                2015,
                4,
                21
            ]
        ],
        "date-time": "2015-04-21T16:31:00Z",
        "timestamp": 1429633860000
    },
    "page": "1534",
    "source": "Crossref",
    "is-referenced-by-count": 26,
    "title": "Autism Occurrence by MMR Vaccine Status Among US Children With Older Siblings With and Without Autism",
    "prefix": "10.1001",
    "volume": "313",
    "author": [
        {
            "given": "Anjali",
            "family": "Jain",
            "affiliation": [
                {
                    "name": "The Lewin Group, Falls Church, Virginia"
                }
            ]
        },
        {
            "given": "Jaclyn",
            "family": "Marshall",
            "affiliation": [
                {
                    "name": "The Lewin Group, Falls Church, Virginia"
                }
            ]
        },
        {
            "given": "Ami",
            "family": "Buikema",
            "affiliation": [
                {
                    "name": "Optum, Eden Prairie, Minnesota"
                }
            ]
        },
        {
            "given": "Tim",
            "family": "Bancroft",
            "affiliation": [
                {
                    "name": "Optum, Eden Prairie, Minnesota"
                }
            ]
        },
        {
            "given": "Jonathan P.",
            "family": "Kelly",
            "affiliation": [
                {
                    "name": "The Lewin Group, Falls Church, Virginia"
                }
            ]
        },
        {
            "given": "Craig J.",
            "family": "Newschaffer",
            "affiliation": [
                {
                    "name": "A. J. Drexel Autism Institute, Drexel University, Philadelphia, Pennsylvania"
                }
            ]
        }
    ],
    "member": "10",
    "container-title": "JAMA",
    "original-title": [],
    "deposited": {
        "date-parts": [
            [
                2016,
                12,
                15
            ]
        ],
        "date-time": "2016-12-15T17:59:31Z",
        "timestamp": 1481824771000
    },
    "score": 1,
    "subtitle": [],
    "short-title": [],
    "issued": {
        "date-parts": [
            [
                2015,
                4,
                21
            ]
        ]
    },
    "references-count": 0,
    "URL": "http://dx.doi.org/10.1001/jama.2015.3077",
    "relation": [],
    "ISSN": [
        "0098-7484"
    ],
    "issn-type": [
        {
            "value": "0098-7484",
            "type": "print"
        }
    ],
    "subject": [
        "Medicine(all)"
    ],
    "id": "a1sc4mgnt7",
    "journalAbbreviation": "JAMA",
    "language": "en-US"
}
```

Where did that reference come from?

**Comment by dsifford** [comment] 2017-10-17 01:26
Getting late here for me, but I'll need to send you a development copy of the plugin to install if you wouldn't mind so that I can dig into the non-obfuscated code.

I'll try to get to it tomorrow if time allows.

**Comment by metallikat36** [comment] 2017-10-17 01:37
I just added that reference as is normally done using a DOI number (doi:10.1001/jama.2015.3077).

This error seems to occur with ALL the references beyond about the 6th in that article. So it may be a systematic bug, and not just an issue with that particular reference. 

I wonder if refreshing the reference list after the last plugin update could have in anyway caused this bug?

Okay, sure I can install another plugin version. Just let me know. 

This bug isn't holding me up in anyway, so no urgency. I don't actually need to edit any reference.

**Comment by dsifford** [comment] 2017-10-17 01:39
Ah, I see... Crossref may have added properties to their API.

Re: Occurring an all after 6th reference.. Hm, very strange indeed. Not sure what could be causing it. Thanks for your patience.

**Comment by dsifford** [comment] 2017-12-14 21:18
@metallikat36 Is this still occurring for you? Can't reproduce this anymore (not sure if I ever was able to to be honest)

**Comment by metallikat36** [comment] 2017-12-14 22:41
I just checked, and indeed the exact bug I posted still occurs when I edit that specific article. It does not seem to happen on other articles (though I did not check extensively). From reference #6 and after, editing most of the references (but not all) triggers the bug. Why some references trigger it and other's don't I have no clue. 

I doubt I would be able to reproduce this from scratch. Maybe just better ignore this until it shows up again.

**Comment by dsifford** [comment] 2017-12-14 22:56
Ah, dang. Yeah, please let me know if you're able to trigger elsewhere. 

Closing this for now. Reopen when needed 👍

**Comment by metallikat36** [comment] 2018-01-21 21:09
Update: I think this bug only happens on references that were inputted using a DOI number.

**Comment by dsifford** [comment] 2018-02-09 01:58
@metallikat36 Is this still happening after the last update?

**Comment by metallikat36** [comment] 2018-02-09 02:05
Yes, the references list still collapses on trying to edit some references on my old articles. But maybe it is a legacy issue now that won't show up anymore? I never knew how to reproduce it in any case. I will update this thread if I ever see it again.

**Comment by dsifford** [comment] 2018-02-09 02:06
Please do! Sorry for the trouble. 

Closing this for now.

**Closed** 2018-02-09 02:06 UTC
Labels: bug, unconfirmed
