### ISSUE TITLE
Date error format preventing use of plugin

### ISSUE THREAD

**Issue by charitablehumans** [dsifford/academic-bloggers-toolkit#407] opened 2018-01-05 03:35 UTC
**ABT Version:** 4.12.1

**PHP Version:** 5.6

**Theme:**

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**
When adding a reference, a hover notice appears saying the date format is incorrect when it isn't, thus making it impossible to add citations. https://www.screencast.com/t/yl5HwBws5Xp

**Actual behavior:**

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment] 2018-01-05 09:01
Duplicate of #405, #404, #401.

Very sorry this is affecting you. The fix will be pushed to wordpress.org shortly. Have to finish one other thing I'm working on first. 

Thanks for your patience.

**Closed by dsifford** 2018-01-05 09:01 UTC

**Comment by dsifford** [comment] 2018-01-06 22:45
@charitablehumans 

The update is still not ready for wordpress.org because there are lots of pretty drastic changes to how custom citation styles are handled that I need to document and test more thouroughly test, but you can download a copy of a beta version from here: https://github.com/dsifford/academic-bloggers-toolkit/releases/tag/v4.13.0-beta

This should resolve your issue with dates.
