### ISSUE TITLE
Problems with displaying references within text

### ISSUE THREAD

**Issue by fmge** [dsifford/academic-bloggers-toolkit#569] opened 2019-06-10 14:08 UTC
ABT Version: 5.1.0
PHP Version: 7.3.6 
Theme: Divi

Plugin List:
GDPR Cookie Consent Banner
Google Analytics for WordPress by MonsterInsights
Google Analytics Opt-Out
InfiniteWP - Client
iThemes Security
Jetpack by WordPress.com
UpdraftPlus 
WP Rocket
Yoast SEO

Browser: Google Chrome (Version: 75.0.3770.80), Firefox (Version: 67.0.1)

Expected behavior: Displaying references in a proper way. 

Actual behavior: Inserted references produce space between the lines:
![01](https://user-images.githubusercontent.com/51640244/59200572-d668e800-8b98-11e9-989e-cb95b497a58f.png)

This is also the case for the tooltip:
![02](https://user-images.githubusercontent.com/51640244/59200655-02846900-8b99-11e9-8529-1682a4541d45.png)

You can find the problem here: https://mgfillinger.com/perceptual-balance-and-aesthetic-preference/

Thanks for your support and this awesome plugin!

Console messages:
commons.js:8 Channel: Error in handleResponse UNK/UNK tabClipper initCompleted
_handleResponsePromise @ commons.js:8
commons.js:8 Channel: Error in handleResponse UNK/UNK tabClipper getCurrentTheme
_handleResponsePromise @ commons.js:8
2commons.js:8 Uncaught (in promise) Error: {}
    at Function.fromAny (commons.js:8)
    at T._handleResponsePromise (commons.js:8)
    at T._handleDispatchResponse (commons.js:8)
    at T._handleMessage (commons.js:8)
    at _listener (commons.js:8)

**Comment by dsifford** [comment] 2019-06-10 15:32
I visited that page and can't reproduce what you're seeing. Were you able to fix?

**Comment by fmge** [comment] 2019-06-10 17:31
It still creates this space between lines. However, I think it is evoked by a conflict with the image. After I moved the image to the block below, this empty rectangle appeared there.

**Comment by dsifford** [comment] 2019-06-10 18:28
Aha, I see. So is it safe to close this issue?

**Comment by fmge** [comment] 2019-06-10 19:06
Sure, as long as there is no other solution on a technical level!

Derek Sifford <notifications@github.com> schrieb am Mo., 10. Juni 2019,
20:28:

**Closed** 2019-06-10 19:14 UTC

**Comment by fmge** [comment] 2019-06-16 19:03
I wanted to let you know that the plugin has still problems to display more than one citations in APA style in a proper way. As you can see on the image, the line break does not work correctly. Do you think it is possible to fix this issue in the future? Thanks!
![Screenshot](https://user-images.githubusercontent.com/51640244/59568330-7df28880-9079-11e9-9a32-ce5bca72ad2d.png)

**Comment by dsifford** [comment] 2019-06-16 19:34
Do you have a link to an affected page that I can take a look at?

**Comment by fmge** [comment] 2019-06-16 20:06
Sure, but you'll have to take a look at it on a smaller screen, e.g., a smartphone. Whenever the screen width is smaller than the citation, the mentioned problem occurs with the line break: https://mgfillinger.com/perceptual-balance-and-aesthetic-preference/

**Comment by dsifford** [comment] 2019-06-16 22:54
A solution for you for the time being would be to just add this to your site's CSS...

```css
.abt-citation {
  display: inline;
}
```

I'll look into getting this patched into the plugin soon.

**Comment by fmge** [comment] 2019-06-17 07:35
Thanks, with this code it works!
