### ISSUE TITLE
Editor toolbar disappears when ABT active

### ISSUE THREAD

**Issue by someonehere15** [dsifford/academic-bloggers-toolkit#39] opened 2016-04-26 23:46 UTC
Hey, just wanted to let you know that I just tried the plugin, and noticed that the editor buttons toolbar disappears when ABT is activated, in visual mode. Not in text mode though.
I tried in in IE and Chrome, and in two different WP setups. Am I missing something or is it a bug?

Nice touch on the jsfiddle in the settings, it's a good idea.

**Comment by dsifford** [comment] 2016-04-27 00:07
Can you send a screenshot? I'm not able to reproduce what you're describing.

**Comment by someonehere15** [comment] 2016-04-27 00:09
![capture](https://cloud.githubusercontent.com/assets/18473637/14837961/1a69e440-0c1d-11e6-9b65-a25e4b468610.JPG)

**Comment by dsifford** [comment] 2016-04-27 00:34
@someonehere15 What other plugins are you using?

On chrome, can you load the page, press F12, click "console" and paste any errors that are there?

**Comment by someonehere15** [comment] 2016-04-27 00:54
Well I am using various plugins, but as I said, I tried it on two completely different sites which have different plugins. These are the errors, and the files are indeed named differently on the folder that the ones mentioned here from what I saw:
```
http://example.com/wp-content/plugins/academic-bloggers-toolkit/lib/css/admin.css?ver=4.5.1 Failed to load resource: the server responded with a status of 404 (Not Found)
load-scripts.php:9 JQMIGRATE: Migrate is installed, version 1.4.0
http://example.com/wp-content/plugins/academic-bloggers-toolkit/lib/js/PeerReviewMetabox.js?ver=4.5.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://example.com/wp-content/plugins/academic-bloggers-toolkit/lib/js/Reflist.js?ver=4.5.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://example.com/wp-content/plugins/academic-bloggers-toolkit/lib/js/tinymce-entrypoint.js?wp-mce-4310-20160418 Failed to load resource: the server responded with a status of 404 (Not Found)
tinymce.min.js:4 Failed to load: http://example.com/wp-content/plugins/academic-bloggers-toolkit/lib/js/tinymce-entrypoint.js
http://example.com/wp-content/plugins/academic-bloggers-toolkit/lib/css/admin.css?ver=4.5.1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by dsifford** [comment] 2016-04-27 00:57
Possibly a cache issue? Is your cite caching aggressively? Try dumping both your local and server cache and try again.

**Comment by dsifford** [comment] 2016-04-27 00:59
Also, just to confirm -- You are installing from WordPress.org, correct? If you install from this repo directly, the plugin won't work. The files need to be compiled.

**Comment by someonehere15** [comment] 2016-04-27 01:22
Yes, you were right, cache. Its working perfectly now. Just a though: wouldn't it be better to place the Import RIS button also on the side widget, and completely eliminate the button on the editor toolbar? there is no need to separate the functions, the widget is much better.
Furthermore, is it expected that I can't insert a reference on the text editing mode, only visual?

**Comment by someonehere15** [comment] 2016-04-27 01:24
Another thing: If I delete the bibliography list from the editor, there's no way of getting it back is there? I can only recreate it if I import a new reference.

**Comment by dsifford** [comment] 2016-04-27 01:46
> Its working perfectly now. 

Phew!

> place the Import RIS button also on the side widget, and completely eliminate the button on the editor toolbar?

I thought that as well, but I'm keeping the button available (for now at least) until I know for sure I'm not going to need it for any other features. I'm imagining that there's going to come a time sooner or later that someone is going to request something that I have no space for on the widget.


> Furthermore, is it expected that I can't insert a reference on the text editing mode, only visual?

Correct. That's actually a weakness of TinyMCE and nothing I have any control over. One thing you'll notice is, if you load the page directly to the text editor and not the visual editor. The loading spinner will spin forever (or until you switch to the visual editor)... That's by design. Otherwise the widget state and the visual editor state get out of sync.

> If I delete the bibliography list from the editor, there's no way of getting it back is there? I can only recreate it if I import a new reference.

Correct. This is also by design. I'd like to keep my plugin completely stateless so that people don't become dependent on it down the road. If I started messing with the database, it would be easier for me, but would be worse for the user because then they would never be able to remove the plugin.

**Comment by someonehere15** [comment] 2016-04-27 09:10
Ok, thanks for clarifying. But I think you misunderstood the last question. I didn't mean if I remove the references from the widget or anything, just that if I delete the generated bibliography from the text, accidentally for instance, and the references are still on the widget, the same session and everything, I cannot regenerate it on the text. Not sure if it's clear now, but I don't think you need states for that.

**Comment by dsifford** [comment] 2016-04-27 16:49
Ah, yeah there's no way to regenerate the bibliography besides doing a ctrl+z. I suppose I might be able to write something in for bibliography regeneration, but I don't think it would serve any better than doing a simple undo. If the bibliography gets deleted and the post is reloaded, it'll be gone for good.

**Comment by dsifford** [comment] 2016-04-29 00:36
Closing this issue for now. If you have any suggestions for making the user experience better in this area, feel free to keep the conversation going :+1:

**Closed** 2016-04-29 00:36 UTC
Labels: invalid, question
