### ISSUE TITLE
Can't get custom style to be recognized

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#400] opened 2017-12-25 17:27 UTC
**ABT Version:** 4.12.0

**PHP Version:** 5.6

**Theme:**GeneratePress

**Plugin List:**

    Very Simple Event List
    Child Theme Configurator
    TablePress
    bbPress
    Sidebar login
    Paypal Donations

Firefox 57

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**
1.  Edit custom style on citationstyles.org
2. Download it.  
3.  FTP it to webroot (FYI: WordPress won't allow a .csl to be uploaded in Media Library).
    File is at http://109.73.239.174/~cookand3/forestpathology.org/mycologia_numbered.csl
4.  Enter it as a custom style URL in ABT settings, then click Update.
5.  It is accepted and shows up in style list when editing a page.

**Actual behavior:**
The URL field in settings goes blank, and the style does not show up when editing pages.

**Console messages:**
```js
// Paste messages here

```
Thinking maybe my edits were bad, to test I downloaded the original style mycologia.csl, renamed it mycologia_copy.csl, and uploaded to same webroot location.  It isn't accepted by ABT either.

**Comment by dsifford** [comment] 2017-12-27 17:22
Thanks for the report.

Not sure what could be the issue here.

> WordPress won't allow a .csl to be uploaded in Media Library

That should be fixed automatically here:
 
https://github.com/dsifford/academic-bloggers-toolkit/blob/bba49e6f4967848b240524b3483186a8865aff71/src/academic-bloggers-toolkit.php#L29-L40

So not sure where the issue is stemming from. 

Focus right now for me is working on adding Gutenberg support, so not sure when I'll be able to dig into this.

**Comment by dsifford** [comment] 2017-12-28 20:44
@glorious1 Just confirming: After clearing your cache, this is still occurring, correct?

**Comment by glorious1** [comment] 2017-12-28 22:09
That’s correct, although not such a big deal now that I have wrapping citations.

**Comment by dsifford** [comment] 2018-01-14 21:12
Revamped how custom styles work in `v4.13.0`.

**Closed by dsifford** 2018-01-14 21:12 UTC
Labels: Bug
