### ISSUE TITLE
Long URLs break pop-up box formatting in Firefox

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#564] opened 2019-05-15 19:18 UTC
**ABT Version:** 

**PHP Version:** 

**Theme:**

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Firefox (66.0.4, Safari 12.1.1

**Expected behavior:** text stays in popup fox

**Actual behavior:** When URL is long, it causes text to overflow the popup box in Firefox, but not in Safari.

**Console messages:**
```js
// Paste messages here

```
See screenshot.  The Kroupova reference has a ridiculously long URL (this is why I liked the old behavior, where the link just had the text Source or PDF or URL).  Safari breaks the URL wherever it needs to to keep it in the box.
![Screen Shot 2019-05-15 at 11 56 45 AM](https://user-images.githubusercontent.com/6004417/57802589-2cb64880-770b-11e9-84ad-fff5f3ff1a5e.png)

**Comment by dsifford** [comment] 2019-10-23 00:13
I think this has already been fixed in a past update. Reopen if that's not the case, but I can't reproduce this anymore.

**Closed by dsifford** 2019-10-23 00:13 UTC
Labels: bug

**Comment by glorious1** [comment] 2019-10-23 14:23
Yes, that is fixed.  Thank you!
