### ISSUE TITLE
5.0.1 update breaks admin section with "Recoverable Fatal Error"

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#539] opened 2019-01-31 14:42 UTC
**ABT Version:** Attempted update to 5.0.1 from last version before 5.0

**PHP Version:** 7.2

**Theme:**

**Plugin List:**
Many plugins, I can't access wp-admin to see them now

**Browser:** Firefox  64.0.2

**Expected behavior:** Update ABT and go on about my business

**Actual behavior:** Now I can't access the admin pages at all; instead I get this error:
"Recoverable fatal error: Object of class WP_Post could not be converted to string in [ . . . ]/wp-content/plugins/academic-bloggers-toolkit/academic-bloggers-toolkit.php on line 73"

**Console messages:**
```js
// Paste messages here
Request to access cookie or storage on “https://cdnsure.com/assets/style” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.
```
I went into plugins via FTP and saw that ABT did update to 5.0.1.  Considering deleting the plugin to see if I can regain admin access.  Please advise.

**Comment by glorious1** [comment] 2019-01-31 15:01
I changed the extension of academic-bloggers-toolkit.php and was able to regain admin access.

**Comment by dsifford** [comment] 2019-01-31 19:31
Duplicate of #538

**Closed by dsifford** 2019-01-31 19:31 UTC

**Comment by glorious1** [comment] 2019-01-31 19:36
I think I do have custom css (probably why this bit me and not others).  Would I be able to revert to the older version to copy out my css?  Wouldn't be database problems?

**Comment by dsifford** [comment] 2019-01-31 19:46
Not after you update unfortunately. The ABT custom CSS was added early in the life of the plugin and it's always been a mistake to have it. It was saved as part of the plugin options and those options get pruned/reset/adjusted on every update. CSS should go in the "customizer" or in a child theme.

**Comment by glorious1** [comment] 2019-01-31 19:56
Well, I was able to access the custom css from the plugin's settings when I reverted to 4.13.3.  I deleted them from there and put them in the child theme's stylesheet as you suggested.

**Comment by dsifford** [comment] 2019-01-31 20:37
Were you able to then update back to the latest version without any problems?

**Comment by glorious1** [comment] 2019-01-31 20:46
I was afraid to try, but since you asked, I went ahead, and had no problems.  I guess deleting the css was the trick.
