### ISSUE TITLE
Reference list in posts doesn't load

### ISSUE THREAD

**Issue by guimaluf** [dsifford/academic-bloggers-toolkit#273] opened 2016-12-22 12:32 UTC
**ABT Version:** 4.9.0
**PHP Version:** 5.6.27

**Theme:** [Thimpress Eduma](https://thimpress.com/product/education-wordpress-theme-education-wp/)

**Plugin List:**
I've deactivated all plugins, only ABT is active.

**Browser:** 
 - Firefox: 50.1.0
 - Google Chrome (Version: 55.0.2883.87 (Official Build) (64-bit))

**Expected behavior:**
When I add a new post or page I would expected to have a reference list where I can create, select and include references.

**Actual behavior:**
The references list widget keep in a loop loading state. I can see lastest changes but the wheel don't stop spinning. Plugin is just not working, nothing to do or interact.

**Console messages:**
No errors on console, unfortunately I'm using Godaddy wordpress hosting, so I have no means to check any specific log. If there is anything I could do to improve debugging, let me know.

**Comment by dsifford** [comment] 2016-12-26 16:51
@guimaluf This is most likely the result of your theme not using the default wordpress editor. 

The plugin is deeply integrated into tinymce, so any visual page builders or custom editors unfortunately are not supported.

**Comment by guimaluf** [comment] 2016-12-27 17:30
@dsifford I've disabled even the theme, changed to default twenty seventeen theme, and even thou it didn't work.

**Comment by dsifford** [comment] 2016-12-27 18:16
@guimaluf That's very strange. You shouldn't have any issues on chrome or firefox.

Any chance you can take a screen recording?

**Comment by guimaluf** [comment] 2016-12-27 18:42
Interesting... I've repeat the whole process of disabling plugins, and now I got a Locale error.
`TypeError: this.sys.retrieveLocale is not a function`
Maybe I forgot to clean cache.

**Comment by dsifford** [comment] 2016-12-27 22:35
I've seen that error pop up in my error tracking logs a whole bunch of times, but I've never been able to reproduce it.

`this.sys.retrieveLocale` is [most definitely a function](https://github.com/dsifford/academic-bloggers-toolkit/blob/28ec535f6da7b970bd345b93c45a2f4e376cec9c/src/lib/js/utils/CSLProcessor.ts#L177)

Not sure where to even begin troubleshooting this since I've been trying to reproduce it for months to no avail.

If you can provide me as much details about your machine/server as possible, that might be helpful.

**Comment by guimaluf** [comment] 2016-12-28 10:59
My WP is in brazilian portuguese(pt_BR) l10n and this is probably the most meaningful detail related with that error.
I'm using is Goddady Wordpress hosting so I do not have much information about my own server :(

After disabling all plugins I could see the ABT interface on post editor. I've tried to insert a random reference(via pubmed) and now I'm getting this:

`TypeError: _this.processor.citeproc is undefined`

If there is any debbuging tool that may provide details to you, let me know.

**Comment by guimaluf** [comment] 2016-12-28 11:48
@dsifford I've changed the site language to US English and now everything went fine!
I could add the reference with no error.

**Comment by dsifford** [comment] 2017-01-04 01:07
@guimaluf Sorry for the delay. That's interesting. Not sure why the locale would trigger this, but that could be something to look into. I'll give it a look soon and report back. 👍

**Comment by dsifford** [comment] 2017-01-04 01:47
@guimaluf I was able to reproduce this! Fantastic!

I'll look into fixing this straight away. Thanks so much for the detailed report. I've been trying to get to the bottom of this for months!

**Comment by dsifford** [comment] 2017-01-04 02:36
@guimaluf fixed in 5f1183d7db1bcc6cfdd885cd9c7d15a53835b0ca -- Pushing the update to wordpress.org now.

**Closed by dsifford** 2017-01-04 02:36 UTC
Labels: Bug
