### ISSUE TITLE
ABT stuck on loading in the editor

### ISSUE THREAD

**Issue by yellowtiramisu** [dsifford/academic-bloggers-toolkit#536] opened 2019-01-23 12:00 UTC
**ABT Version:** 4.13.3

**PHP Version:** 7.3

**Theme:** Independent Publisher 2

**Plugin List:**
- Akismet
- Jetpack
- Loginizer

**Browser:** Safari (Version: 12.0.2) and Google Chrome (Version: 71.0.3578.98)

**Expected behavior:** For the plugin to load in the right-hand side bar of the WordPress Editor

**Actual behavior:** Plugin would not load and is instead stuck on the loading animation, as shown here:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/13222850/51605215-7215f680-1f1f-11e9-9fbc-ad3858ca86bb.png">

**Console messages:**
```js
// Paste messages here

```
 No error messages.

**Comment by dsifford** [comment] 2019-01-23 18:00
Duplicate of #534 #533 #523.

Working on an update now. Should be ready soon.

**Closed by dsifford** 2019-01-23 18:00 UTC
