### ISSUE TITLE
TypeError: this.registry.citationreg.citationById[i[0]] is undefined

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#464] opened 2018-05-19 13:47 UTC
**ABT Version:** 4.13.3

**PHP Version:** 7.0.3

**Theme:** GeneratePress

**Plugin List:**
I tested with all other plugins deactivated, no effect.

**Browser:** Google Chrome (Version: xxx) Firefox 60.0

 
**Expected behavior:** Select a reference, click the add button, it goes into the page

**Actual behavior:** Popup dialog with "TypeError: this.registry.citationreg.citationById[i[0]] is undefined"

**Console messages:** 
```js
// Paste messages here
Backend: JQMIGRATE: Migrate is installed, version 1.4.1
Frontend: nothing
```
Note: This is not happening on all pages (only found on 1 so far but I have many pages).  Content was not copied and pasted like audioscavenger.  I had imported the references a few months ago and added many to the text successfully.  Now I went back to do more and getting the error.

The only change in the interim is that I changed the site URL because it is now the live site.  This required changing many links in the site.

I'm guessing I will have to destroy references on the page and start over.

**Comment by dsifford** [comment] 2018-05-19 16:29
Yes, unfortunately since this is not something you can reproduce, it sounds like an issue stemming from the page itself.

**Comment by glorious1** [comment] 2018-05-20 14:56
Wow, this page is giving me fits with ABT.  I deleted all the references and re-added them.  When I saved, the citations all appeared at the very beginning of the page.  Then I noticed there were 28 instead of 25 that were imported - 3 were duplicated with minor differences.  I went into the RIS format settings of my bibliography program (Bookends) and deleted some unneeded fields (which were blank lines in the offending references).

Then when I deleted all and imported, there were 25.  Whew.  But when I added references, and viewed the page, the citations were there, but clicking on them did nothing and there was no bibliography.

So I deleted all again.  I saved the page, exited it, then reopened it.  The references were all back in ABT, and there were 28 rather than 25!!  I did this twice to verify.

Is there any way to completely nuke ABT on this page so it can't remember anything?  Is my database messed up?

**Comment by dsifford** [comment] 2018-10-01 21:52
Noted. I'm busy with midterms the next few weeks but hopefully when other commitments die down I'll be able to dive into this and see.

The fix for this will ideally happen when I get a chance to update for gutenberg.

**Comment by Ysenberg** [comment] 2018-10-05 15:40
We have the same issue. The error message is the following : 

Une erreur inattendue s'est produite
TypeError: this.registry.citationreg.citationById[i[0]] is undefined
S'il vous plait, rapportez cette erreur incluant les étapes pour la déclencher, ici : 
https://github.com/dsifford/academic-bloggers-toolkit/issues

To make the message appear, we try to introduce any of the references in our article.

**Comment by sash3x** [comment] 2019-01-07 21:32
has this issue been resolved? I am also have the same error. 
TypeError: this.registry.citationreg.citationById[i[0]] is undefined

only on two pages.

**Comment by dsifford** [comment] 2019-01-07 22:10
Plugin is bricked and broken completely until I can push the next update out (which will be soon)... just sit tight.

**Comment by dsifford** [comment] 2019-01-13 18:11
I can't seem to figure out how to reproduce this in the updated version I'm working on so I'm going to mark this as "resolved" for now. If after the update this is still persisting, reopen this issue and we'll revisit.

**Closed by dsifford** 2019-01-13 18:11 UTC
