### ISSUE TITLE
Clash with Advanced Custom Fields plugin

### ISSUE THREAD

**Issue by floaltvater** [dsifford/academic-bloggers-toolkit#115] opened 2016-08-17 13:27 UTC
Hi,
I updated the plugin to 4.0.0. When the Advance Custom Fields plugin is activated, the Reference List meta box keeps loading indefinitely, and the Browser console spits out:

    TypeError: tinyMCE.activeEditor.dom is undefined                    post-new.php (line 2232, column 19)
    tinyMCE.activeEditor.dom.addStyle("\r\n                .mce-content-body .h1, .m...
    _|
   
(where "_|" should signify a small curved arrow)

and

    SecurityError: The operation is insecure.                             app-ccbb152ab5.js (line 1)
    ...=s.host,t.currentCount=t.countUnreadItems(),t.badgeCount=t.countUnseenItems(),t....

Any ideas what could cause this? Could it be a setting in ACF that I set on my site? Or a bigger issue?

The problem appears in regular posts and ACF modified custom post types.

Thanks.

**Comment by dsifford** [comment] 2016-08-17 15:14
I've had an issue with Advanced Custom Fields [in the past](https://github.com/dsifford/academic-bloggers-toolkit/issues/40). I'll see if I can sort this one out as well.

**Comment by dsifford** [comment] 2016-08-17 15:20
@floaltvater Can you list the precise steps you take in order to have an error triggered? I can't get it to happen by just activating the custom fields plugin.

Thanks

**Comment by dsifford** [comment] 2016-08-17 15:29
@floaltvater would disabling my plugin for "acf" post types be an acceptable solution? I'm not sure what someone would use that plugin for so it's hard for me to make that decision without some background.

**Comment by floaltvater** [comment] 2016-08-17 20:58
Currently, all the steps it takes is, activate ACF, Add New post or Edit post, triggers error, also when there's already a citation.

It would certainly be nice to be able to use ABT with ACF post types. However, I understand that it is hard to figure out and protect against any interference.

In my case right now, I would prefer to have it, as it would allow our group members to put references on their profile pages (which use ACF) using ABT. But they don't even know yet that this tool exists and it's a rather small additional effort for them to manually add a reference once in a while.

So, I would say it would be a bummer, but absolutely acceptable.

**Comment by dsifford** [comment] 2016-08-17 21:05
I see.

Can you try going to the page that you'd add references to on a profile and type this in the console and show me what the output is:

`wpActiveEditor`

and then

`tinymce.editors`

To guard against ACF "stealing" the references on post editor pages, I had to make this plugin only communicate with tinymce editors with the id of `content`.

The author of ACF chose to mount a hidden tinymce editor on every admin page and use that to store settings for some reason and that hidden editor is the root of all evil.

**Comment by floaltvater** [comment] 2016-08-17 21:14
`wpActiveEditor` gave `null`

`tinymce.editors` gave

    [Object { documentBaseUrl="https://www.ocf.berkeley...ate/wp_neaton/wp-admin/",  settings={...},  id="content",  mehr...},
    Object { documentBaseUrl="https://www.ocf.berkeley...ate/wp_neaton/wp-admin/",  settings={...},  id="acf_settings",  mehr...}]

That sounds like very bad coding practice from the ACF side :(

**Comment by floaltvater** [comment] 2016-08-17 21:28
Trying this again resulted in `"content"` for `wpActiveEditor`. Same for `tinymce.editors` as far as I can tell. Not sure what I did the first time. Sorry for the confusion.

**Comment by dsifford** [comment] 2016-08-17 22:40
Hm... Yeah, I'll have to play around with it. It's tough to run tests when I don't have any custom fields set up. 

Would there be any way for you to share the custom fields you have for the group member pages? A screenshot maybe?

> That sounds like very bad coding practice from the ACF side :(

Can't say that. It's an enormous plugin with (as I recall) over a million active installs. He looks to be quite experienced with PHP so I'm sure there's a reason why he's doing what he's doing.

Me on the other hand.... I try to stay as far away from PHP as I possibly can, due to the fact that I find it miserable to work with. That's the unfortunate compromise of developing a plugin for WordPress; I'm forced to write some PHP 😦

**Comment by floaltvater** [comment] 2016-08-17 22:49
This is the current setup. It is only used for a custom post type. But should probably work on normal posts as well. The External link and External instructions only shows if the External page is set to true.

![group-member-acf](https://cloud.githubusercontent.com/assets/6099666/17755945/d3259d9a-6491-11e6-9049-92c17c0f2950.png)

If you need more details, let me know. Thanks!

**Comment by dsifford** [comment] 2016-08-17 23:17
@floaltvater None of the fields listed use the WYSIWYG editor in the image above. Is that correct? Where at would you want to use my plugin on that page?

Also, can you share the conditionals for those fields that you are using? Thanks!

**Comment by floaltvater** [comment] 2016-08-17 23:30
Correct, no WYSIWYG editor. I still have the regular post editor visible, where they can enter their research interests etc. This is where the publications would go. I had a WYSIWYG editor at first to specifically put in their publications, but decided to make it less convoluted for them and just have one box for whatever they want to put in.

Conditionals:
- Name, Portrait, Email, Office, External Page: No
- External Link, Instructions - External: Yes, If External Page is equal to checked.
- Instructions - Internal: Yes, If External Page is not equal to checked.

**Comment by dsifford** [comment] 2016-08-18 00:08
> Correct, no WYSIWYG editor.

Ah, okay... This shouldn't be a problem then.

Thanks for confirming the fields and conditionals... Let me play around for a bit and see if I can cause my plugin to break. 👍

**Comment by dsifford** [comment] 2016-08-18 00:43
@floaltvater As long as you don't plan on using the plugin while your _creating_ custom fields (on the custom field editor page), I'm pretty sure it should work fine.

I can't seem to get it to break, and I'm trying quite hard!

That said, I was never able to get it to break the same way you did, so I could have missed your issue altogether. 

Would you be willing to try out this next version on your site to make sure I have it handled prior to me pushing out the update to everybody?

**Comment by dsifford** [comment] 2016-08-18 02:51
If so...

[academic-bloggers-toolkit.zip](https://github.com/dsifford/academic-bloggers-toolkit/files/424049/academic-bloggers-toolkit.zip)

Thanks for the help 😄

**Comment by floaltvater** [comment] 2016-08-18 06:08
When I have version 4.0.1 and the ACF activated, I get the same result (`TypeError tinyMCE.activeEditor.dom is undefined`). I even deleted all of the ACF groups, without effect. I am not editing any ACF groups at the point I Add or Edit a post. But the meta box is still not loading. Could I do any debugging on my side to try to track it down?

When I deactivate ACF I get the follwing error three times (and the meta box is also not loading):

    TypeError: t.children is undefined                           index.j...r=4.0.1 (line 14)
    ...(t,e){var i="id";e&&(i="title");for(var s="",r=t.children,n=0,a=r.length;n<a;n++...

**Comment by dsifford** [comment] 2016-08-18 19:05
@floaltvater see #118 

Closing this because I have no way of reproducing this. Sorry for the inconvenience.

**Closed by dsifford** 2016-08-18 19:05 UTC
Labels: bug

**Comment by elliotcondon** [comment] 2016-08-29 05:29
Hi @floaltvater 

Elliot here from ACF
How's it going? I think I've fixed this issue.

If possible, can you please download and test the latest build of ACF PRO (5.4.3 RC1)?
​
1. Login to your account online: http://www.advancedcustomfields.com/my-account
2. Click on the ‘see all versions’ link next to your license
3. Download the latest 5.4.3 RC1 version​​

Please let me know if this fixes the issue for you

**Comment by floaltvater** [comment] 2016-08-30 19:43
Hi @elliotcondon 
Thanks for tuning in here, and sorry for my delayed response. I am currently not an ACF PRO user, so I don't know if I could download that version anyway (and I don't have an account yet). However, version 4.4.8 of the free version seems to have fixed the issue for me. So whatever you did there presumably also works for the PRO version. Thanks so much for your quick response to that!
