### ISSUE TITLE
Problem with RIS file import and disappearing references

### ISSUE THREAD

**Issue by jourkameleont** [dsifford/academic-bloggers-toolkit#166] opened 2016-09-23 12:15 UTC
![ris](https://cloud.githubusercontent.com/assets/22134572/18784783/af977b26-8194-11e6-9eff-09fb6822f3da.PNG)

**ABT Version:** 4.4.0

**PHP Version:** 5.6

**Theme:** Baskerville

**Plugin List:**
Contact form 7
Custom Facebook Feed
Custom Post Type Widgets
Jetpack
Simple yearly archive
Open external links in a new window
Akismet

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**

**Actual behavior:**
I can´t import RIS-files, see screenshot. I know the files are OK, they worked before I updated. I can´t remove the buggy import either. 

Second problem: often as soon as I leave the editing page, publish or just switch to html editor, all of the added references disappear from the reference list and from the html. Which means I can't edit published posts at all without losing the references.

**Console messages:**
```js
// Paste messages here
```

**Comment by dsifford** [comment] 2016-09-23 12:33
@jourkameleont 

Need a few things:

1. Can you confirm your version of php?
2. What version of chrome are you running?
3. Any console warnings (hit F12 on the affected page to check)

Thanks

**Comment by dsifford** [comment] 2016-09-23 12:36
Additionally, can you post a screencast of your second issue? That's hard to believe since switching from the visual editor to the text editor fundamentally doesn't even come close to modifying the state of the reference list under the hood. (Not calling you a liar, just find it hard to believe and need clarification to make sure I'm understanding you correctly)

**Comment by jourkameleont** [comment] 2016-09-23 13:11
Sorry, I am not using Chrome but Firefox, version 48.0.2.

I can´t find any warnings and I don't know how to check PHP version.

It's hard do screenshot the disappearance, it simply is an empty reference list and no references in the text. I also find it hard to believe but nonetheless it has happened several times...

**Comment by dsifford** [comment] 2016-09-23 13:43
> I can´t find any warnings

On firefox, to access the console you need to press <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>i</kbd>.

If you can find any messages there at all, that would be the most helpful.

>  I don't know how to check PHP version

I've added a check to the options page. Just go to that page and it'll be printed there.

> It's hard do screenshot the disappearance, it simply is an empty reference list and no references in the text. I also find it hard to believe but nonetheless it has happened several times...

If you can't get a screen recording of this happening, then a list of detailed steps to trigger this error would be necessary for me to try and reproduce it. Can't fix it if I can't reproduce it!

Thanks

**Comment by jourkameleont** [comment] 2016-09-23 16:30
F12 works as well but I can't find any warnings or other messages.

Great, PHP version 7.0.11.

**Comment by dsifford** [comment] 2016-09-23 16:34
Kudos on using PHP 7! You're one of the few smart cookies out there 😄  (PHP 7 offers a big speed boost from its predecessors) 

Hm, that's a shame Re: no console messages.

Can you send me a copy of the RIS file so I can try to replicate your issue exactly? dereksifford@gmail.com

Thanks

**Comment by dsifford** [comment] 2016-09-23 18:06
Closing since I can't reproduce this.

**Closed by dsifford** 2016-09-23 18:06 UTC
Labels: Invalid
