### ISSUE TITLE
Cannot read property 'properties' of undefined when inserting references with PMID 

### ISSUE THREAD

**Issue by gillespieza** [dsifford/academic-bloggers-toolkit#118] opened 2016-08-18 13:04 UTC
Hi there

Since the latest update, when I try to insert a reference using a pubmed ID/DOI, instead I now get a popup alert saying "Cannot read property 'properties' of undefined" and the animated spinner just sits there in the background and nothing happens... No console errors logged either.

This is happening even if I switch to the default TwentySixteen Theme and de-activate all other plugins. 

Screenshot attached, fwiw.

![untitled-1](https://cloud.githubusercontent.com/assets/11884699/17731924/d1ce745c-646f-11e6-85d7-57fc839c813e.png)

WordPress: WPMU, 4.6
Academic Toolkit: 4.0.0

**Comment by dsifford** [comment] 2016-08-18 13:15
Duplicate of #115 

I think I may have an idea on what's going on. What style are you using?

Also can you clear your browser cache and try again once more?

**Comment by gillespieza** [comment] 2016-08-18 13:28
I'm using style AMA (American Medical Association), but choosing a random other style makes no difference. 

It seems that the error messages are different, depending on the browser.

I switched to FireFox (Private Window) and the popup error changed to "this.registry.citationreg.citationById[r[0]] is undefined".

Chrome Incognito mode error reads "Cannot read property 'properties' of undefined"

In Internet Explorer, the error reads "Unable to get property 'properties' of undefined or null reference".

Clearing my cache made no difference.

**Comment by dsifford** [comment] 2016-08-18 13:30
Does this happen when creating a brand new post, or is it just with old posts?

**Comment by gillespieza** [comment] 2016-08-18 13:32
Ah, how interesting... it works if I create a brand new post ... Cool.

**Comment by dsifford** [comment] 2016-08-18 13:33
On the old post, can you try to click "refresh reference list" and see if that fixes it?

**Comment by gillespieza** [comment] 2016-08-18 13:36
Nope, same error. Shall I try "Delete All References" and see if I can insert a new one?

**Comment by dsifford** [comment] 2016-08-18 13:39
If you can afford to, that will for sure work. Otherwise, if you can afford to wait, I may be able to fix "refresh reference list" so that it fixes the issue non-destructively.

This issue is caused because before the update, I wasn't storing reference data 100% properly. I fixed that in the update, but all old posts are still using cached reference data unaware of the fix

**Comment by gillespieza** [comment] 2016-08-18 13:43
Great. I'll just continue with creating a new post in the mean time. Thanks for being so responsive!

**Comment by gillespieza** [comment] 2016-08-18 13:58
FYI, deleting all references fixes the old post.

**Comment by dsifford** [comment] 2016-08-18 15:59
@gillespieza Do you know what version the plugin was in when you created one of the posts that trigger the error? 

I just rolled back my local version to 3.4.3 and created a bunch of test posts and tried editing them with 4.0.0 and everything works fine.

Thanks

**Comment by gillespieza** [comment] 2016-08-18 16:44
Sadly, I don't remember. The plugin did sit unused for several months until I "got around to it", but that's all I can tell you. If I manage to reproduce this on an independent site (not my WPMU installation), I'll let you know...

**Comment by dsifford** [comment] 2016-08-18 16:50
Sounds good. Thanks.

In the meantime, I'm going to install and test `3.2.0 -> 3.3.0 -> 3.4.0 -> 4.0.0` to see if I can trigger the issue that way.

**Comment by gillespieza** [comment] 2016-08-18 16:51
I was also using WP < 4.6.

**Comment by dsifford** [comment] 2016-08-18 18:59
@gillespieza @floaltvater

I went back several versions and incrementally created test-posts using each of the versions. 

![image](https://cloud.githubusercontent.com/assets/5240018/17786620/9f79154a-6553-11e6-9594-b70c24b1d3d5.png)

Then, I installed the latest version and attempted to get it to fail in the same way you both were describing for each of the test posts.... I could not reproduce your issues.

At this point, I'm not sure this is going to be something that I can fix, unfortunately. There's just no way I can even try to attempt fixing something I have no ability to reproduce. 

I apologize for the inconvenience, again, but you should be safe from here on out. The plugin has come a long way from what it was when I first started working on it. I've made lots and lots of mistakes in the beginning (when I was very inexperienced with software engineering and design patterns). The good news is: Most of those mistakes have been corrected. The unfortunate casualty of those mistakes is the root cause of both of your issues. 

Again, if delete all your references on the pages that are giving you trouble (using the `Delete all references` button) and then create a new reference list, you should not have any more issues. The same goes for new posts created from here on out.

I'm going to mark this issue as "resolved" due to the fact that I can't reproduce it. If either of you are able to figure out a more detailed way of producing the errors, feel free to re-open this.

**Closed by dsifford** 2016-08-18 18:59 UTC

**Comment by gillespieza** [comment] 2016-08-18 19:01
I totally understand. Thanks for being so helpful. As long as it works now (which it does), I'm a happy camper. :)
