### ISSUE TITLE
Cannot manually edit any reference except for author

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#412] opened 2018-01-15 17:10 UTC
**ABT Version:** 4.13.0

**PHP Version:** 7.0.27

**Theme:**GeneratePress

**Plugin List:**
All deactivated

**Browser:** Firefox 57

**Expected behavior:** Be able to edit.

**Actual behavior:** Can edit authors only.  All other fields locked

**Console messages:** None
```js
// Paste messages here

```

**Comment by dsifford** [comment] 2018-01-15 17:21
Sorry for the trouble. I'll take a look at this as soon as I can.

**Comment by dsifford** [comment] 2018-01-15 19:58
Duplicate of #411

**Closed by dsifford** 2018-01-15 19:58 UTC
Labels: Bug
