### ISSUE TITLE
Autocite Not Working in Block Editor

### ISSUE THREAD

**Issue by bockal** [dsifford/academic-bloggers-toolkit#563] opened 2019-05-14 15:55 UTC
**ABT Version:** academic-bloggers-toolkit.5.1.0

**PHP Version:**  Running PHP version: 7.2.18

**Theme:** GeneratePress

 https://cinci360.com/wp-content/uploads/2019/05/broken.png
**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)  Chrome 74.0.3729.131 (Official Build) (64-bit)

**Expected behavior:** Autocite function to populate reference data based on URL

 Nothing
**Actual behavior:**

**Console messages:** No JS errors. https://cinci360.com/2019/05/14/1628-ltd/
```js
// Paste messages here

```

**Comment by dsifford** [comment] 2019-05-14 20:40
Which URL are you attempting to cite?

The URL autocite is hit or miss. On the backend, it just crudely scrapes the page you enter for metadata information using a handful of known common metadata tags. If they don't exist, nothing will return besides (IIRC) just the accessed date.

**Comment by bockal** [comment] 2019-05-14 20:44
It wouldn't cite any of the academic URLs I tried today.
https://cinci360.com/2019/05/14/excel-supplements/

Or any I tried to re-add here:
https://cinci360.com/2019/05/14/1628-ltd/

Wish I had a bigger brain to help on the backend. Unfortunately, I just make messy websites.

**Comment by dsifford** [comment] 2019-05-14 20:53
Hm. What specifically did you enter and specifically which search box did you enter it?

Can you list the steps so that I can try to reproduce?

Thanks

**Comment by mrvinceo** [comment] 2019-06-18 08:19
Hi @dsifford ,

I seem to be having the same issue on a multi-site network; everything was working, right up until I demoed it to our subject academics the other week 🙄. I've had the same issue once before, which came down to a conflict with the development version of the Gutenberg editor still being enabled (despite running in core), but that's now deleted, which seemed to fix it for a while, and no new plugins have been added or updated since... it's odd that this has now come back.

To clarify, I can add new items (journals, books, websites etc. either manually or via the doi number), and they appear fine under un-cited items. When I position the cursor and add it, it goes into the cited items list, but nothing else happens in the paragraph block or reference list. From the console, it looks like the issue is here: 

`Uncaught (in promise) TypeError: Cannot read property 'rebuildProcessorState' of undefined
    at t.value (processor.ts:87)
    at actions.ts:107
    at s (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.t.<computed> [as next] (runtime.js:97)
    at redux-routine.min.js?ver=3.0.4:1`

I'm not good with js, but perhaps this means something to you? Full log also attached if it helps.

I love that this issue hasn't broken any existing citations though - very nice, and many thanks for your excellent work on this!

[spaces.oca.ac.uk-1560845251751.log](https://github.com/dsifford/academic-bloggers-toolkit/files/3300473/spaces.oca.ac.uk-1560845251751.log)

**Comment by dsifford** [comment] 2019-06-18 18:07
@mrvinceo Hm, difficult to tell what might be going on without being able to reproduce this. Any chance you might be able to record your screen with this happening or something?

**Comment by mrvinceo** [comment] 2019-06-19 10:20
No problem; here it is: https://youtu.be/_BKMsQaV5vo

Not sure if it might be related to some issues I've seen around Gutenberg (https://github.com/WordPress/gutenberg/issues/12324) as that issue also references the redux-runtime.min.js but I've been through the steps in that issue queue and the same issue occurs.

**Comment by dsifford** [comment] 2019-06-19 14:59
Thanks. I'll look into this soon.

**Comment by dsifford** [comment] 2019-06-19 16:30
In the meantime, try disabling all your other plugins to make sure it's not a conflict with one of those.

**Comment by mrvinceo** [comment] 2019-06-21 14:12
Thanks, I'll give that a go!

**Comment by dsifford** [comment] 2019-06-22 01:25
Report back either way to let me know what happens :+1:

**Comment by dsifford** [comment] 2019-10-22 23:47
Are any of you still experiencing this issue? Sorry for the radio silence.

**Comment by bockal** [comment] 2019-10-23 03:48
To be honest I haven't had time to publish any cited blog work in the last
six months. It's not you, it's me. You should sell this tool to genealogy
bloggers on wordpress though - it's amazing. Most groups have funds to pay
for this sort of thing too. There are thousands of genealogy researchers
and they all convene in about 10 different facebook groups. If you were
drumming up business, that would be my starting point for this plugin.

Aubrey Backscheider, (513) 800-7366
Cinci360.com <http://cinci360.com/> 3D Modeling Company
GOOGLE Business Partner

**Comment by dsifford** [comment] 2019-10-23 14:09
No worries. I'm gonna go ahead and close this issue then until someone else can drum it up again since I can't seem to reproduce it anymore. Reopen if you run into it again.

**Closed by dsifford** 2019-10-23 14:09 UTC

**Comment by dsifford** [comment] 2019-10-31 16:54
This is a separate issue. See #582
