### ISSUE TITLE
Export References?? I need to export the references we inputted into one page to then IMPORT for another page. Is this possible? Or is there a master back end list of all references I can see or export back out? 

### ISSUE THREAD

**Issue by rojabella660** [dsifford/academic-bloggers-toolkit#313] opened 2017-03-20 15:08 UTC
**ABT Version:** 4.10.0

**PHP Version:** 5.6

**Theme:**

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**

**Actual behavior:**

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment] 2017-03-20 16:44
@rojabella660 This does not exist currently. 

It's been suggested and I'm considering adding it but I'm not sure when I'll be able to get to it.

Sorry for the trouble.

**Comment by dsifford** [comment] 2017-04-21 15:09
Closing. Dupe of #272

**Closed by dsifford** 2017-04-21 15:09 UTC
