### ISSUE TITLE
a is null

### ISSUE THREAD

**Issue by alinakrt** [dsifford/academic-bloggers-toolkit#425] opened 2018-01-26 11:30 UTC
**ABT Version:** 4.13.2

**PHP Version:** 5.6

**Theme:**

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**

**Actual behavior:**

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment] 2018-01-26 16:47
@alinakrt I'm not sure what this means. Can you clarify your issue with as many details as possible?

**Comment by alinakrt** [comment] 2018-01-29 08:06
I'm sorry to have been so laconic. The message „a is null” popped up when I
tried editing the homepage of my (Wordpress) website. The same message
stated I should report the error to a certain link, indicating GitHub. I'm
unaware of what caused this error message to appear and it hasn't appeared
since.

--
Alina Kartman
redactor revista *Semnele timpului *
www.semneletimpului.ro

**Comment by dsifford** [comment] 2018-01-29 18:50
Hmm.. Thanks for clarifying @alinakrt 

I'm going to close this issue thread for now since that seems to be a single, fluke occurrence. Feel free to reopen this if this happens again and becomes reproducible.

**Closed by dsifford** 2018-01-29 18:50 UTC
