### ISSUE TITLE
Can't add different citations with the same title

### ISSUE THREAD

**Issue by chrisaldrich** [dsifford/academic-bloggers-toolkit#241] opened 2016-11-17 05:17 UTC
I'm circling back on this issue (https://github.com/dsifford/academic-bloggers-toolkit/issues/161) though I thought it had been cleared up, but I've retested my original post. Perhaps we hadn't tested it well enough originally, or something has changed in the erstwhile to change the behavior?

In any case, here's what I'm seeing presently (with the latest Version 4.7.2, WP 4.6.1):
Books with the same title, but different authors and different other meta data can be input, but when actually inserting the citation, the superscript number for the first book input with that matching book title is appearing. 

The desired book reference does (now) appear in the list of references (it wasn't before), but appears under the subsection "Uncited items". This seems like the best/most intuitive way to display it from a UI perspective.

Example:
http://boffosocko.com/2016/07/25/introduction-to-complex-analysis-ucla-extension/

Several of these books have the same title, namely "Complex Analysis".
Most show up improperly when cited as 3 (the first one I input), while incomprehensibly to me, 6 and 8 show up properly instead of as 3 as the others do that have the same title. 8 and 9 on the last book at the bottom both appear properly though 9 has a longer title which differentiates it from the other.

**Comment by dsifford** [comment] 2016-11-17 15:25
Hi @chrisaldrich 

Any chance you have that list of references saved as a RIS file that I can play around with?

I've been hesitant to add strict, deep equality comparisons to the reference parser because scenarios exist where the exact same citation can be acquired using different sources (eg PMID and DOI) and, because the sources don't always send precisely the same information, deep equality will fail and the citation will be allowed to be inserted twice.

I'll look into fixing this further though without deep equality matching for your specific scenario if you can provide that RIS file.

Thanks

**Comment by dsifford** [comment] 2016-11-20 16:24
@chrisaldrich Were you able to provide that RIS file so I can fix?

**Comment by chrisaldrich** [comment] 2016-11-20 23:45
<a href="https://github.com/dsifford/academic-bloggers-toolkit/issues/241#issuecomment-261787964" class="u-in-reply-to"></a>@dsifford Here's the RIS file for your convenience: https://dl.dropboxusercontent.com/u/126498/complex_analysis.ris

Since a lot of of the comparison is done by unique identifiers (DOI, PMID, ISBN) is there a way to keep these numbers and do the comparison based on them? Ideally, publishers distinguish editions and copies properly via ISBN so though systems might have slightly different meta data in other fields, if ISBNs are exactly the same, then they should be the same works. It's usually very rare for major publishers to have the same ISBN (and typically only happens when there are very minute differences between texts). This still won't fix the problem for works prior to the mid 1970s, but will work for the majority of contemporary references.

**Comment by dsifford** [comment] 2016-11-21 00:01
@chrisaldrich Thanks. I'll check into this tomorrow.

Re: your question..

Yep, it would definitely be possible using unique identifiers. This won't be guaranteed to capture all manually entered citation duplicates since those fields are all optional, but I think the automatic citations are probably the bulk of the issue anyway.

I'll keep ya posted.

**Comment by dsifford** [comment] 2016-11-22 00:34
@chrisaldrich Looking into this now.

What's immediately striking is that it appears to work just fine for `american-medical-association` style. Can you confirm this on your side as well?

Digging deeper now...

**Comment by dsifford** [comment] 2016-11-22 00:35
@chrisaldrich It also is working for `chicago-full-note`.. What style exactly are you using?

**Comment by chrisaldrich** [comment] 2016-11-22 19:49
<a href="https://github.com/dsifford/academic-bloggers-toolkit/issues/241#issuecomment-262112164" class="u-in-reply-to"></a>@dsifford I've generally been using one of the IEEE styles though I had used others. I tried both the AMA and Chicago styles you mentioned on my original post, but had the same issue.

Curious to see if there was a difference, I imported my own RIS file into a new test post and was surprised to see the issue didn't replicate itself. In my original post that was showing the issue, I had gone in and MANUALLY added all of the references one at a time using the ISBN look up for the meta data. When doing it this way, the issue definitely shows up. I suspect that the issue arises in how the data is being imported and stored between the two methods, bulk import and manual one-at-a-time input, presuming these are different.

A further difference I'm seeing between the two methods (manual vs. RIS bulk import) is in how names are being displayed (seemingly without respect to style/display). For some reason when doing references manually inputting first name, middle name, last name (as indicated in the modal box) causes the style sheets to mix up the order of the names when output.  This mixing up of the names doesn't seem to be an issue when importing from an RIS file.

For example, when I do a reference manually for the author Lars V. Ahlfors, the output reference shows the name incorrectly as: L. Ahlfors Valerian
When doing it via RIS import the name appears correctly as L. V. Ahlfors

I imagine that it's possible that the way in which the data is being input/stored between the two methods is potentially causing the problem.

**Comment by dsifford** [comment] 2016-11-22 23:02
Thanks for the clarification, that's really helpful!

> In my original post that was showing the issue, I had gone in and MANUALLY added all of the references one at a time using the ISBN look up for the meta data. When doing it this way, the issue definitely shows up.

I'll go and try the one-by-one approach and see if I can get that to trigger the issue.

> A further difference I'm seeing between the two methods (manual vs. RIS bulk import) is in how names are being displayed (seemingly without respect to style/display). For some reason when doing references manually inputting first name, middle name, last name (as indicated in the modal box) causes the style sheets to mix up the order of the names when output. This mixing up of the names doesn't seem to be an issue when importing from an RIS file.

I tried your Lars Ahlfors example and was not able to reproduce. Can you explain exactly how it is you input the name in the manual field?

> I imagine that it's possible that the way in which the data is being input/stored between the two methods is potentially causing the problem.

All the data, no matter where it comes from, resolves to a common storage type, so this should hopefully be an easy fix once we track down the bug. 👍

**Comment by dsifford** [comment] 2016-11-22 23:49
Update: figured out the issue with manually adding individual citations with similar names. It was a silly mistake on my end. That issue should be fixed on the next update.

However, that issue should not cause the author naming issue that you've mentioned. Can you please elaborate further on that?

**Comment by dsifford** [comment] 2016-11-23 00:36
Scratch the "silly mistake" part. It's a much more complicated issue. Might take a while

**Comment by dsifford** [comment] 2016-11-23 19:08
Update: I think I finally got it...

![image](https://cloud.githubusercontent.com/assets/5240018/20575208/4a09ba90-b186-11e6-91c2-fa739fd60d36.png)

Need to test a bit more, but it's close. 👍

**Closed** 2016-11-26 22:11 UTC
Labels: Bug, Next Release

**Comment by dsifford** [comment] 2016-11-26 22:38
Let me know how that works for you @chrisaldrich

**Comment by chrisaldrich** [comment] 2016-11-30 17:32
<a href="https://github.com/dsifford/academic-bloggers-toolkit/issues/241" class="u-in-reply-to"></a>Double-checked this morning and it seems to be working properly for manual input now.  Thanks @dsifford!
