### ISSUE TITLE
Error in the date when adding manually reference

### ISSUE THREAD

**Issue by HoussenMoshine** [dsifford/academic-bloggers-toolkit#401] opened 2017-12-28 12:08 UTC
**ABT Version:** 4.12.1

**PHP Version:** 5.6.4

**Theme:*Hueman*

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: 62)

**Expected behavior: Insert reference manually**

**Error : It's say that the date format is no valid when adding a manuel reference. Even there are not date or the format is correct. I've tested in several sites and the error persist. When there are not date, following message is showing  : **

`Cannot read property 'reduce' of undefined`

Screen Capture

https://imgur.com/a/e20Yi

**No error message in the console**
```js
// Paste messages here

```

**Comment by dsifford** [comment] 2017-12-28 15:41
Definitely a bug. 

I moved around some stuff involving the date parser before the last update, so that's likely the cause.

Thanks for the report.

**Comment by dsifford** [comment] 2017-12-28 15:46
On a different note: Thanks for volunteering to translate! 

I'll try to get both this fix and your translations pushed out as soon as I can.

**Comment by glorious1** [comment] 2017-12-28 16:32
I noticed this today also.  If I try to edit a reference in ABT, I can't save it because it says the date is the wrong format, though it's just a journal article with a simple year.

**Comment by dsifford** [comment] 2017-12-28 17:20
This will be fixed shortly. Found the issue. Tackling it now.

**Closed** 2017-12-28 20:53 UTC
Labels: Bug

**Comment by dsifford** [comment] 2018-01-06 22:42
@HoussenMoshine @glorious1 

The update is still not ready for wordpress.org because there are lots of pretty drastic changes to how custom citation styles are handled that I need to document and test more thouroughly test, but you can download a copy of a beta version from here: https://github.com/dsifford/academic-bloggers-toolkit/releases/tag/v4.13.0-beta

This should resolve your issue with dates.

**Comment by glorious1** [comment] 2018-01-07 00:34
Thanks!

I’ve never updated a plugin manually. When I try to do it in the WordPress interface, uploading the zip, it says the directory already exists.  Is it safe to delete the academic-bloggers-toolkit directory in the plugins folder without losing settings?

**Comment by dsifford** [comment] 2018-01-07 05:08
@glorious1 Yes. Delete the existing folder and then install the zip and you're good to go.

Alternatively, you can uninstall the plugin using WordPress and then reinstall using the zip keeping in mind that if you choose to do it that way, you'll lose all of your saved settings (default citation style, etc).
