### ISSUE TITLE
Tooltips with multiple citations do not use ascending order.

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#516] opened 2018-11-04 22:05 UTC
See this screenshot:
![image](https://user-images.githubusercontent.com/17968340/47970461-817d5600-e03a-11e8-8f9b-6120ab1bce73.png)
Note that citation 4 is not first in that tooltip. Bug. Not major. 

See this video for steps to reproduce:
https://www.youtube.com/watch?v=iXr2YOhZJRY&feature=youtu.be

The same video also documents a second bug which I think is unrelated. I will open a second thread for that.

**Comment by glorious1** [comment] 2018-11-10 18:50
FYI metallikat36, I discovered this some thing and reported it a year or so ago.  What I found was, when I am making a citation for multiple references, they appear in the order I click to select them.  It
's tedious if you have a lot of references, as for me they are not listed in any particular order.  But try clicking them in alphabetical order.

**Comment by dsifford** [comment] 2018-12-14 03:34
Dupe of #421 ... Keep the conversation going there.

I'll try to have this sorted out in the next update.

**Closed by dsifford** 2018-12-14 03:34 UTC
